unstable_features = true

max_width = 81
use_small_heuristics = "Max"

blank_lines_lower_bound = 0
blank_lines_upper_bound = 3

combine_control_expr = false

# control_brace_style = "ClosingNextLine"

tab_spaces = 4

use_field_init_shorthand = true
